config/routes.rb
Rails.application.routes.draw do
  root 'billboard_charts#index'

  resources :billboard_charts do
    resources :artists
  end

   resources :artist do
      resources :songs 
   end

  delete "/billboard_chart/:id", to: "billboard_charts#destroy", as: "destroy_the_billboard_chart"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  belongs_to :billboard_chart
  has_many :songs, dependent: :destroy
end

app/models/billboard_chart.rb
class BillboardChart < ApplicationRecord
  has_many :artists, dependent: :destroy
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :artist
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_artist, only: [:show, :edit, :update, :destroy]
  before_action :set_billboard_chart

  def index
   @artists = @billboard_chart.artists
  end

  def show
  end

  def new
    @artist = @billboard_chart.artists.new
    render partial: "form"
  end

  def create
    @artist = @billboard_chart.artists.new(artist_params)
    if @artist.save
      redirect_to [@billboard_chart, @artist]
    else
      render :new
    end
  end

  def edit
    render partial: "form"
  end

  def update
    if @artist.update(artist_params)
      redirect_to [@billboard_chart, @artist]
    else
      render :edit
    end
  end

  def destroy 
    @artist.destroy
    redirect_to billboard_chart_path(@billboard_chart)
  end

  private
    def artist_params
      params.require(:artist).permit(:name)
    end

    def set_artist
      @artist =  Artist.find(params[:id])
    end

    def set_billboard_chart
      @billboard_chart = BillboardChart.find(params[:billboard_chart_id])
    end
    
end

app/controllers/billboard_charts_controller.rb
class BillboardChartsController < ApplicationController

  before_action :set_billboard_chart, only: [:show, :edit, :destroy, :update]
  

  def index
    @billboard_charts = BillboardChart.all
  end

  def show
    # @billboard_chart = BillbardChart.find(params[:id]) is being called before action
  end

  def new
    @billboard_chart = BillboardChart.new 
    render partial: "form"
  end

  def create
    @billboard_chart = BillboardChart.new(billboard_charts_params)
    if @billboard_chart.save
      redirect_to billboard_charts_path
    else
      render :new
    end
  end

  def edit
    # @billboard_chart = BillbardChart.find(params[:id]) is being called before action
    render partial: "form"
  end

  def update
    if @billboard_chart.update(billboard_charts_params)
      redirect_to @billboard_chart
      # redirect_to billboard_charts_path(@billboard_chart)
    else
      render :edit
    end
  end

  def destroy
    # @billboard_chart = BillbardChart.find(params[:id]) is being called before action
    @billboard_chart.destroy
    redirect_to billboard_charts_path
  end

  private

  def billboard_charts_params
    params.require(:billboard_chart).permit(:title)
  end

  def set_billboard_chart
    @billboard_chart = BillboardChart.find(params[:id])
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: [:show, :update, :edit, :destroy]
  before_action :set_artist

  def index
    @songs = @artist.songs
  end

  def show
  end

  def new
    @song = @artist.songs.new
    render partial: "form"
  end

  def create
    @song = @artist.songs.new(songs_params)
    if @song.save
       redirect_to [@artist]
    else 
      render :new
    end
  end

  def edit
    render partial: "form"
  end

  def destroy
    @song.destroy
     redirect_to artist_songs_path(@artist)
  end
  private

  def songs_params
    params.require(:song).permit(:song_title, :album_name)
  end

  def set_song
    @song = Song.find(params[:id])
  end

  def set_artist
    @artist = Artist.find(params[:artist_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/billboard_charts_helper.rb
module BillboardChartsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/artists/_form.html.erb
<h1><%= @artist.id ? "Edit Artist" : "Create Artist"%></h1>
<%= form_for [@billboard_chart, @artist] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name%>
  <%= f.label :genre %>
  <%= f.text_field :genre%>
  <%= f.submit %>
<% end %>

app/views/artists/edit.html.erb
<h1>Artists#edit</h1>
<p>Find me in app/views/artists/edit.html.erb</p>

app/views/artists/index.html.erb
<h1><%= @billboard_chart.title %> Artists</h1>

<% @artists.each do |artist| %>
    
    <%=  link_to artist.name, [@billboard_chart, artist] %>
    
    <% end %>
    <%= link_to 'Create New Artist', new_billboard_chart_artist_path(@billboard_chart) %>
  </ul>

app/views/artists/new.html.erb
<h1>Artists#new</h1>
<p>Find me in app/views/artists/new.html.erb</p>

app/views/artists/show.html.erb
<h1>Artists#show</h1>
<h1><%= @artist.name %></h1>
<hr />
<p>What would you like to do?</p>
<%= link_to 'Back to all Artists', billboard_chart_artists_path(@billboard_chart) %>
<br />
<%= link_to 'View Songs', artist_songs_path(@artist) %>
<br />
<%= link_to 'Edit Artist', edit_billboard_chart_artist_path([@billboard_chart, @artist]) %>
<br />
<%= link_to 'Delete Artist', [@billboard_chart, @artist], method: :delete %>

app/views/billboard_charts/_form.html.erb
<h1>Top 100 List Form</h1>
<%= form_for @billboard_chart do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.submit %>
<% end %>

app/views/billboard_charts/edit.html.erb
<h1>BillboardCharts#edit</h1>
<p>Find me in app/views/billboard_charts/edit.html.erb</p>

app/views/billboard_charts/index.html.erb
<h1>Click a Chart to View Content</h1>
<%= link_to "Create a new Top 100 List", new_billboard_chart_path %>
<ul>
  <% @billboard_charts.each do |chart| %>
    <%= link_to chart.title, chart %>
    <%# <%= link_to 'New Chart', new_billboard_chart_path %>

    <% end %>
  </ul>

app/views/billboard_charts/new.html.erb
<h1>BillboardCharts#new</h1>
<p>Find me in app/views/billboard_charts/new.html.erb</p>

app/views/billboard_charts/show.html.erb
<h1><%= @billboard_chart.title %></h1>
<hr />
<p>What would you like to do?</p>
<%= link_to 'View all Charts', billboard_charts_path %>
<br />
<%= link_to 'View Artists', billboard_chart_artists_path(@billboard_chart) %>
<br />
<%= link_to 'Edit Chart', edit_billboard_chart_path(@billboard_chart) %>
<br />
<%= link_to 'Delete Chart', @billboard_chart, method: :delete %>

app/views/charts/edit.html.erb
<h1>Charts#edit</h1>
<p>Find me in app/views/charts/edit.html.erb</p>

app/views/charts/new.html.erb
<h1>Charts#new</h1>
<p>Find me in app/views/charts/new.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Billboard</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/songs/_form.html.erb
<h1>Song</h1>
<%= form_for [@artist, @song] do |f| %>
  <%= f.label :song_title %>
  <%= f.text_field :song_title %>
  <%= f.label :album_name %>
  <%= f.text_field :album_name %>
  <%= f.submit %>
<% end %>

app/views/songs/edit.html.erb
<h1>Songs#edit</h1>
<p>Find me in app/views/songs/edit.html.erb</p>

app/views/songs/index.html.erb
<h1> Songs </h1>
<%= link_to "Add New Song", new_artist_song_path %>
<ul>
<% @songs.each do |song| %>
    <%=  p "Title: #{song.song_title} Album: #{song.album_name}" %>
    <br>
    
    <%= link_to 'Delete Song', [@artist, @song], method: :delete  %>

    <% end %>
  </ul>

app/views/songs/new.html.erb
<h1>Songs#new</h1>
<p>Find me in app/views/songs/new.html.erb</p>

app/views/songs/show.html.erb
<h1>Songs#show</h1>
<p>Find me in app/views/songs/show.html.erb</p>